name: Automatic Pull request

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'title of example'
        required: true
      body:
        description: 'description of example'
        required: true
      upstreamRepo:
        description: 'Upstream repo name'
        required: true
      account:
        description: 'repo name'
        required: true

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create PR
        run: |
          gh pr create --repo ${{ github.event.inputs.account }}/${{ github.event.inputs.upstreamRepo }} --head ${{ github.event.inputs.account }}:${{ github.ref }} --base main --title "${{ github.event.inputs.title }}" --body "${{ github.event.inputs.body }}"
        env:
          GITHUB_TOKEN: ${{ secrets.token }}