name: Automatic Pull request

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'title of example'
        required: true
      body:
        description: 'description of example'
        required: true
      upstreamRepo:
        description: 'Upstream repo'
        required: true

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Create PR
        run: |
          echo "${GITHUB_REF#refs/heads/}"
          gh pr create --repo ${{GITHUB_REPOSITORY}} --head ${GITHUB_REF#refs/heads/} --base ${{ github.event.inputs.upstreamRepo }}:main --title "${{ github.event.inputs.title }}" --body "${{ github.event.inputs.body }}"
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
